name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-package
      run: sudo apt-get -y install bison flex
    - name: submodule
      run: git submodule init && git submodule update
    - name: cmake
      run: mkdir build && cd build && cmake --version && cmake ..
    - name: make
      run: cd build && make -j 4
    - name: test1
      run: cd build && ./project1/test1
    - name: test
      run: cd build/test && ./gemm && ./conv2d
